project_id = "duktebslocooppxedanv"

[functions.generate-event-pairings]
verify_jwt = false

[functions.calculate-event-winners]
verify_jwt = false

[functions.update-player-handicap]
verify_jwt = false

[functions.seed-data]
verify_jwt = false

[functions.populate-data]
verify_jwt = false

[functions.setup-admin-accounts]
verify_jwt = false

[functions.reset-all-passwords]
verify_jwt = false
