import { useParams, useNavigate } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import {
  Calendar, MapPin, Users, Ticket, Trophy, Award, Shuffle, TrendingDown,
  ClipboardCheck, Package, Lock, Car, UserCheck, ChevronRight, Pencil, Plus, RefreshCw, Clock, Download
} from "lucide-react";
import html2canvas from "html2canvas";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { useState, useEffect } from "react";
import { toast } from "sonner";
import AssignContestantDialog from "@/components/tour/AssignContestantDialog";
import WinnerResultsDialog from "@/components/event/WinnerResultsDialog";

const EventDetail = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [showAssign, setShowAssign] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [finalizing, setFinalizing] = useState(false);
  const [showFinalizeConfirm, setShowFinalizeConfirm] = useState(false);
  const [startType, setStartType] = useState("tee_time");
  const [firstTee, setFirstTee] = useState("07:00");
  const [interval, setInterval] = useState("8");
  const [activeTab, setActiveTab] = useState("overview");
  const [userId, setUserId] = useState<string | null>(null);
  const [checkingIn, setCheckingIn] = useState(false);
  const [showCheckinDialog, setShowCheckinDialog] = useState(false);
  const [showCartDialog, setShowCartDialog] = useState(false);
  const [showCaddyDialog, setShowCaddyDialog] = useState(false);
  const [cartNumber, setCartNumber] = useState("");
  const [selectedContestantForCart, setSelectedContestantForCart] = useState("");
  const [selectedContestantForCaddy, setSelectedContestantForCaddy] = useState("");
  const [selectedCaddy, setSelectedCaddy] = useState("");
  const [showWinners, setShowWinners] = useState(false);
  const [exporting, setExporting] = useState(false);

  const handleExportPDF = async () => {
    setExporting(true);
    try {
      const content = document.createElement("div");
      content.style.cssText = `width:800px;padding:40px;background:white;font-family:sans-serif;color:#1a1a1a;`;
      content.innerHTML = `
        <div style="text-align:center;margin-bottom:24px;border-bottom:2px solid #1a6b3c;padding-bottom:16px">
          <h1 style="font-size:24px;font-weight:700;color:#1a6b3c;margin:0">${event?.name}</h1>
          <p style="color:#666;margin:4px 0">${event?.event_date} · ${(event?.courses as any)?.name}</p>
          <p style="color:#666;margin:0;font-size:13px">${(event?.tours as any)?.name ?? ""}</p>
        </div>
        <h2 style="font-size:16px;color:#1a6b3c;margin-bottom:12px">Leaderboard</h2>
        <table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:24px">
          <thead><tr style="background:#1a6b3c;color:white">
            <th style="padding:8px 12px;text-align:left">Rank</th>
            <th style="padding:8px 12px;text-align:left">Nama</th>
            <th style="padding:8px 12px;text-align:center">HCP</th>
            <th style="padding:8px 12px;text-align:center">Gross</th>
            <th style="padding:8px 12px;text-align:center">Net</th>
          </tr></thead>
          <tbody>
            ${(leaderboard ?? []).slice(0, 20).map((row: any, i: number) => `
              <tr style="background:${i % 2 === 0 ? '#f9f9f9' : 'white'}">
                <td style="padding:6px 12px;font-weight:${row.rank_net <= 3 ? '700' : '400'}">
                  ${row.rank_net <= 3 ? ['🥇','🥈','🥉'][row.rank_net-1] : row.rank_net}
                </td>
                <td style="padding:6px 12px">${row.profiles?.full_name ?? "Unknown"}</td>
                <td style="padding:6px 12px;text-align:center">${row.hcp ?? '-'}</td>
                <td style="padding:6px 12px;text-align:center">${row.total_gross ?? '-'}</td>
                <td style="padding:6px 12px;text-align:center;font-weight:600;color:#1a6b3c">${row.total_net ?? '-'}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <p style="font-size:11px;color:#999;text-align:center;border-top:1px solid #eee;padding-top:12px;margin-top:24px">
          Generated by CFGolf · ${new Date().toLocaleDateString('id-ID')}
        </p>
      `;
      document.body.appendChild(content);
      const canvas = await html2canvas(content, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
      document.body.removeChild(content);
      const link = document.createElement("a");
      link.download = `${event?.name}-results.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
      toast.success("Export berhasil!");
    } catch (err: any) {
      toast.error("Export gagal: " + err.message);
    }
    setExporting(false);
  };

  useEffect(() => {
    supabase.auth.getUser().then(({ data: { user } }) => {
      if (user) setUserId(user.id);
    });
  }, []);

  // --- Queries ---
  const { data: event, isLoading } = useQuery({
    queryKey: ["event", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("events")
        .select("*, courses(name, location, par, id), tours(name, id, organizer_club_id)")
        .eq("id", id!)
        .single();
      if (error) throw error;
      return data;
    },
    enabled: !!id,
  });

  const { data: contestants, refetch: refetchContestants } = useQuery({
    queryKey: ["event-contestants", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("contestants")
        .select("*, profiles(full_name, avatar_url, handicap), tournament_flights(flight_name)")
        .eq("event_id", id!);
      if (error) throw error;
      return data;
    },
    enabled: !!id,
  });

  const { data: tickets } = useQuery({
    queryKey: ["event-tickets", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("tickets")
        .select("*, clubs(name), profiles(full_name)")
        .eq("event_id", id!)
        .order("ticket_number");
      if (error) throw error;
      return data;
    },
    enabled: !!id,
  });

  const { data: checkins, refetch: refetchCheckins } = useQuery({
    queryKey: ["event-checkins", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("event_checkins")
        .select("*, contestants(profiles(full_name))")
        .eq("event_id", id!)
        .order("checked_in_at", { ascending: false });
      if (error) throw error;
      return data;
    },
    enabled: !!id,
  });

  const { data: cartAssignments, refetch: refetchCarts } = useQuery({
    queryKey: ["event-carts", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("golf_cart_assignments")
        .select("*, contestants(profiles(full_name))")
        .eq("event_id", id!)
        .order("cart_number");
      if (error) throw error;
      return data;
    },
    enabled: !!id,
  });

  const { data: caddyAssignments, refetch: refetchCaddies } = useQuery({
    queryKey: ["event-caddies", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("caddy_assignments")
        .select("*, contestants(profiles(full_name)), profiles!caddy_assignments_caddy_id_fkey(full_name)")
        .eq("event_id", id!);
      if (error) throw error;
      return data;
    },
    enabled: !!id,
  });

  const { data: pairings, refetch: refetchPairings } = useQuery({
    queryKey: ["event-pairings", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("pairings")
        .select("*, pairing_players(*, contestants(*, profiles(full_name, handicap)))")
        .eq("event_id", id!)
        .order("group_number");
      if (error) throw error;
      return data;
    },
    enabled: !!id,
  });

  const { data: leaderboard, refetch: refetchLeaderboard } = useQuery({
    queryKey: ["event-leaderboard", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("event_leaderboard")
        .select("*, profiles:player_id(full_name)")
        .eq("event_id", id!)
        .order("rank_net", { ascending: true });
      if (error) throw error;
      return data;
    },
    enabled: !!id,
  });

  const { data: results, refetch: refetchResults } = useQuery({
    queryKey: ["event-results", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("event_results")
        .select("*, contestants(profiles(full_name)), tournament_winner_categories(category_name, calculation_type)")
        .eq("event_id", id!)
        .order("rank_position");
      if (error) throw error;
      return data;
    },
    enabled: !!id,
  });

  // Check if user is contestant & checked in
  const myContestant = contestants?.find(c => c.player_id === userId);
  const myCheckin = checkins?.find(ci => ci.contestant_id === myContestant?.id);
  const isCheckedIn = !!myCheckin;

  // Check if user is club admin for the event's organizing club
  const { data: isEventAdmin } = useQuery({
    queryKey: ["event-admin-check", id, userId],
    queryFn: async () => {
      const clubId = (event?.tours as any)?.organizer_club_id;
      if (!clubId || !userId) return false;
      // 1. Check club admin (owner/admin)
      const { data: memberRole } = await supabase
        .from("members")
        .select("role")
        .eq("club_id", clubId)
        .eq("user_id", userId)
        .in("role", ["owner", "admin"])
        .maybeSingle();
      if (memberRole) return true;
      // 2. Check event role (tournament_director or event_coordinator)
      const { data: eventRole } = await supabase
        .from("event_roles")
        .select("role")
        .eq("event_id", id!)
        .eq("user_id", userId)
        .in("role", ["tournament_director", "event_coordinator"])
        .maybeSingle();
      if (eventRole) return true;
      // 3. Fallback: platform super admin
      const { data: sysAdmin } = await supabase
        .from("system_admins")
        .select("id")
        .eq("user_id", userId)
        .eq("is_active", true)
        .maybeSingle();
      return !!sysAdmin;
    },
    enabled: !!event && !!userId,
  });


  const showAdminActions = !!isEventAdmin;

  // --- Handlers ---
  const invokeWithAuth = async (fnName: string, body: any) => {
    const { data: sessionData } = await supabase.auth.getSession();
    const token = sessionData?.session?.access_token;
    return supabase.functions.invoke(fnName, {
      body,
      headers: token ? { Authorization: `Bearer ${token}` } : undefined,
    });
  };

  const handleGeneratePairings = async () => {
    if (!id) return;
    setGenerating(true);
    try {
      const { data, error } = await invokeWithAuth("generate-event-pairings", {
        event_id: id, start_type: startType, first_tee_time: firstTee, interval_minutes: parseInt(interval) || 8,
      });
      if (error) toast.error(error.message || "Failed");
      else if (data?.error) toast.error(data.error);
      else { toast.success(`Generated ${data.groups_created} groups`); refetchPairings(); }
    } catch (err: any) { toast.error(err.message); }
    finally { setGenerating(false); }
  };

  const handleFinalizeEvent = async () => {
    if (!id) return;
    setFinalizing(true);
    setShowFinalizeConfirm(false);
    try {
      // Step 1: Hitung pemenang
      const { data: winnersData, error: winnersErr } =
        await invokeWithAuth("calculate-event-winners", { event_id: id });
      if (winnersErr) {
        toast.error(
          "Edge function tidak tersedia. Event akan di-set completed tanpa kalkulasi pemenang."
        );
        // Tetap lanjut ke step 3
      } else if (winnersData?.error) {
        toast.error("Gagal menghitung pemenang: " + winnersData.error);
        setFinalizing(false);
        return;
      }

      // Step 2: Update tournament HCP (hanya jika step 1 berhasil)
      if (!winnersErr) {
        const { error: hcpErr } = await invokeWithAuth(
          "update-player-handicap",
          { event_id: id }
        );
        if (hcpErr) {
          toast.error("HCP update gagal: " + hcpErr.message);
        }
      }

      // Step 3: Set event completed (selalu dijalankan)
      const { error: statusErr } = await supabase
        .from("events")
        .update({ status: "completed" })
        .eq("id", id);
      if (statusErr) {
        toast.error("Gagal update status: " + statusErr.message);
        setFinalizing(false);
        return;
      }

      toast.success("Event berhasil di-finalize!");
      queryClient.invalidateQueries({ queryKey: ["event", id] });
      refetchResults();
    } catch (err: any) {
      toast.error(err.message ?? "Terjadi kesalahan");
    } finally {
      setFinalizing(false);
    }
  };

  const handleSelfCheckin = async () => {
    if (!myContestant || !id) return;
    setCheckingIn(true);
    try {
      const nextBagDrop = (checkins?.length ?? 0) + 1;
      const nextLocker = (checkins?.length ?? 0) + 101;
      await supabase.from("event_checkins").insert({
        event_id: id,
        contestant_id: myContestant.id,
        bag_drop_number: nextBagDrop,
        locker_number: nextLocker,
      });
      toast.success(`Checked in! Bag #${nextBagDrop}, Locker #${nextLocker}`);
      refetchCheckins();
      setShowCheckinDialog(false);
    } catch (err: any) { toast.error(err.message); }
    finally { setCheckingIn(false); }
  };

  const handleAssignCart = async () => {
    if (!id || !selectedContestantForCart || !cartNumber) return;
    await supabase.from("golf_cart_assignments").insert({
      event_id: id,
      contestant_id: selectedContestantForCart,
      cart_number: parseInt(cartNumber),
    });
    toast.success("Cart assigned!");
    refetchCarts();
    setShowCartDialog(false);
    setCartNumber("");
    setSelectedContestantForCart("");
  };

  const handleAssignCaddy = async () => {
    if (!id || !selectedContestantForCaddy || !selectedCaddy) return;
    await supabase.from("caddy_assignments").insert({
      event_id: id,
      contestant_id: selectedContestantForCaddy,
      caddy_id: selectedCaddy,
    });
    toast.success("Caddy assigned!");
    refetchCaddies();
    setShowCaddyDialog(false);
    setSelectedContestantForCaddy("");
    setSelectedCaddy("");
  };

  // Fetch staff for caddy dropdown
  const { data: clubStaff } = useQuery({
    queryKey: ["club-staff-caddies", event?.tours],
    queryFn: async () => {
      const clubId = (event?.tours as any)?.organizer_club_id;
      if (!clubId) return [];
      const { data } = await supabase
        .from("club_staff")
        .select("*, profiles(full_name)")
        .eq("club_id", clubId)
        .eq("status", "active");
      return data ?? [];
    },
    enabled: !!event,
  });

  const statusColors: Record<string, string> = {
    draft: "border-muted-foreground/30 text-muted-foreground",
    registration: "border-accent/40 text-accent",
    checkin: "border-accent/40 text-accent",
    playing: "border-primary/40 text-primary",
    completed: "border-primary/60 text-primary",
  };

  const formatTeeTime = (t: string | null) => {
    if (!t) return "—";
    try { return new Date(t).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: false }); }
    catch { return t; }
  };

  if (isLoading) return (
    <div className="bottom-nav-safe space-y-4 p-4">
      <Skeleton className="h-8 w-48" />
      <Skeleton className="h-40 w-full rounded-xl" />
    </div>
  );

  if (!event) return (
    <div className="bottom-nav-safe p-4 text-center text-muted-foreground">Event not found</div>
  );

  const usedTickets = tickets?.filter(t => t.status !== "available").length ?? 0;

  return (
    <div className="bottom-nav-safe">
      {/* Header */}
      <div className="p-4">
        <button onClick={() => navigate(`/tour/${(event.tours as any)?.id}`)} className="mb-2 text-xs text-muted-foreground hover:text-foreground transition-colors">
          ← {(event.tours as any)?.name}
        </button>
        <div className="flex items-start justify-between">
          <div>
            <h1 className="font-display text-xl font-bold">{event.name}</h1>
            <div className="mt-1 flex flex-wrap gap-x-3 text-xs text-muted-foreground">
              <span className="flex items-center gap-1"><Calendar className="h-3 w-3" /> {event.event_date}</span>
              <span className="flex items-center gap-1"><MapPin className="h-3 w-3" /> {(event.courses as any)?.name}</span>
            </div>
          </div>
          <Badge variant="outline" className={`text-[10px] ${statusColors[event.status] ?? ""}`}>{event.status}</Badge>
        </div>
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-4 gap-2 px-4 pb-3">
        <div className="golf-card p-2.5 text-center">
          <Users className="mx-auto h-3.5 w-3.5 text-primary" />
          <p className="text-base font-bold">{contestants?.length ?? 0}</p>
          <p className="text-[9px] text-muted-foreground">Players</p>
        </div>
        <div className="golf-card p-2.5 text-center">
          <ClipboardCheck className="mx-auto h-3.5 w-3.5 text-accent" />
          <p className="text-base font-bold">{checkins?.length ?? 0}</p>
          <p className="text-[9px] text-muted-foreground">Check-ins</p>
        </div>
        <div className="golf-card p-2.5 text-center">
          <Shuffle className="mx-auto h-3.5 w-3.5 text-primary" />
          <p className="text-base font-bold">{pairings?.length ?? 0}</p>
          <p className="text-[9px] text-muted-foreground">Groups</p>
        </div>
        <div className="golf-card p-2.5 text-center">
          <Trophy className="mx-auto h-3.5 w-3.5 text-accent" />
          <p className="text-base font-bold">{(event.courses as any)?.par ?? "—"}</p>
          <p className="text-[9px] text-muted-foreground">Par</p>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex gap-2 overflow-x-auto px-4 pb-3 scrollbar-none">
        {/* Self check-in button */}
        {myContestant && !isCheckedIn && (
          <Button size="sm" className="h-7 shrink-0 gap-1 text-[11px]" onClick={() => setShowCheckinDialog(true)}>
            <ClipboardCheck className="h-3 w-3" /> Check In
          </Button>
        )}
        {/* Scorecard button */}
        {myContestant && isCheckedIn && (
          <Button
            size="sm"
            variant={event?.status === "completed" ? "outline" : "default"}
            className={`h-7 shrink-0 gap-1 text-[11px] ${
              event?.status === "completed"
                ? "opacity-50 cursor-not-allowed border-muted-foreground/30 text-muted-foreground"
                : ""
            }`}
            onClick={() => navigate(`/event/${id}/scorecard`)}
            disabled={event?.status === "completed"}
          >
            <Pencil className="h-3 w-3" />
            {event?.status === "completed" ? "Score Locked" : "Input Score"}
          </Button>
        )}
        {/* Admin-only buttons */}
        {showAdminActions && (
          <>
            <Button size="sm" variant="outline" className="h-7 shrink-0 gap-1 text-[11px]" onClick={() => setShowAssign(true)}>
              <Users className="h-3 w-3" /> Assign
            </Button>
            {event?.status !== "completed" ? (
              <Button
                size="sm"
                className="h-7 shrink-0 gap-1 text-[11px] bg-primary"
                onClick={() => setShowFinalizeConfirm(true)}
                disabled={finalizing}
              >
                <Trophy className="h-3 w-3" />
                {finalizing ? "Finalizing…" : "Finalize Event"}
              </Button>
            ) : (
              <Badge className="text-[10px] bg-primary/20 text-primary border-primary/30">
                ✓ Completed
              </Badge>
            )}
          </>
        )}
        <Button size="sm" variant="outline" className="h-7 shrink-0 gap-1 text-[11px]" onClick={() => setShowWinners(true)}>
          <Trophy className="h-3 w-3" /> Results
        </Button>
        {event?.status === "completed" && (
          <Button size="sm" variant="outline" className="h-7 shrink-0 gap-1 text-[11px]" onClick={handleExportPDF} disabled={exporting}>
            <Download className="h-3 w-3" /> {exporting ? "..." : "Export"}
          </Button>
        )}
      </div>

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab} className="px-4">
        <TabsList className="w-full overflow-x-auto flex">
          <TabsTrigger value="overview" className="flex-1 text-[11px]">Overview</TabsTrigger>
          <TabsTrigger value="checkin" className="flex-1 text-[11px]">Check-in</TabsTrigger>
          <TabsTrigger value="pairings" className="flex-1 text-[11px]">Pairings</TabsTrigger>
          <TabsTrigger value="leaderboard" className="flex-1 text-[11px]">Board</TabsTrigger>
        </TabsList>

        {/* OVERVIEW */}
        <TabsContent value="overview" className="space-y-4 pt-2">
          {/* Pairing Approval Setting */}
          {showAdminActions && event?.status !== "completed" && (
            <div className="golf-card p-3 flex items-center justify-between">
              <div>
                <p className="text-xs font-medium">Pairing Approval</p>
                <p className="text-[9px] text-muted-foreground">
                  Review sebelum dipublikasikan ke pemain
                </p>
              </div>
              <Switch
                checked={event?.pairing_approval_required ?? false}
                onCheckedChange={async (val) => {
                  await supabase
                    .from("events")
                    .update({ pairing_approval_required: val })
                    .eq("id", id!);
                  queryClient.invalidateQueries({ queryKey: ["event", id] });
                  toast.success(val
                    ? "Pairing approval aktif"
                    : "Pairing langsung dipublikasikan");
                }}
              />
            </div>
          )}

          <Section title="Contestants" icon={Users} count={contestants?.length}>
            {contestants?.length === 0 && <EmptyState text="No contestants" />}
            {contestants?.slice(0, 10).map((c) => (
              <div key={c.id} className="golf-card flex items-center gap-3 p-3">
                <div className="flex h-7 w-7 items-center justify-center rounded-full bg-primary/10 text-xs font-semibold text-primary">
                  {(c.profiles as any)?.full_name?.charAt(0) ?? "?"}
                </div>
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-medium truncate">{(c.profiles as any)?.full_name ?? "Unknown"}</p>
                  <p className="text-xs text-muted-foreground">HCP {c.hcp ?? "—"} · {(c.tournament_flights as any)?.flight_name ?? "—"}</p>
                </div>
                <Badge variant="outline" className="text-[10px]">{c.status}</Badge>
              </div>
            ))}
            {(contestants?.length ?? 0) > 10 && <p className="text-xs text-muted-foreground text-center py-1">+{(contestants!.length) - 10} more</p>}
          </Section>

          <Section title="Tickets" icon={Ticket} count={tickets?.length} sub={`${usedTickets} assigned`}>
            {tickets?.length === 0 && <EmptyState text="No tickets" />}
            {tickets?.slice(0, 6).map((t) => (
              <div key={t.id} className="golf-card flex items-center justify-between p-3">
                <div>
                  <p className="text-sm font-medium">#{t.ticket_number} · {(t.clubs as any)?.name}</p>
                  <p className="text-xs text-muted-foreground">{t.assigned_player_id ? (t.profiles as any)?.full_name : "Unassigned"}</p>
                </div>
                <Badge variant="outline" className="text-[10px]">{t.status}</Badge>
              </div>
            ))}
          </Section>

          <Section title="Results" icon={Award} count={results?.length}>
            {results?.length === 0 && <EmptyState text="No results yet" />}
            {results?.map((r) => (
              <div key={r.id} className="golf-card flex items-center gap-3 p-3">
                <div className="flex h-7 w-7 items-center justify-center rounded-full bg-accent/10 text-xs font-bold text-accent">#{r.rank_position}</div>
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-medium truncate">{(r.contestants as any)?.profiles?.full_name ?? "Unknown"}</p>
                  <p className="text-xs text-muted-foreground">{(r.tournament_winner_categories as any)?.category_name} · {r.score_value}</p>
                </div>
              </div>
            ))}
          </Section>
        </TabsContent>

        {/* CHECK-IN */}
        <TabsContent value="checkin" className="space-y-4 pt-2">
          <Section title="Check-ins" icon={ClipboardCheck} count={checkins?.length}>
            {checkins?.length === 0 && <EmptyState text="No check-ins yet" />}
            {checkins?.map((ci) => (
              <div key={ci.id} className="golf-card p-3 space-y-1">
                <div className="flex items-center justify-between">
                  <p className="text-sm font-medium">{(ci.contestants as any)?.profiles?.full_name ?? "Unknown"}</p>
                  <span className="text-[10px] text-muted-foreground">{new Date(ci.checked_in_at).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}</span>
                </div>
                <div className="flex gap-3 text-xs text-muted-foreground">
                  {ci.bag_drop_number != null && (
                    <span className="flex items-center gap-1"><Package className="h-3 w-3" /> Bag #{ci.bag_drop_number}</span>
                  )}
                  {ci.locker_number != null && (
                    <span className="flex items-center gap-1"><Lock className="h-3 w-3" /> Locker #{ci.locker_number}</span>
                  )}
                </div>
              </div>
            ))}
          </Section>

          <Section title="Golf Cart" icon={Car} count={cartAssignments?.length}>
            {showAdminActions && (
              <Button size="sm" variant="outline" className="w-full h-7 gap-1 text-[11px] mb-2" onClick={() => setShowCartDialog(true)}>
                <Plus className="h-3 w-3" /> Assign Cart
              </Button>
            )}
            {cartAssignments?.length === 0 && <EmptyState text="No carts assigned" />}
            {cartAssignments?.map((ca) => (
              <div key={ca.id} className="golf-card flex items-center justify-between p-3">
                <div className="flex items-center gap-2">
                  <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary/10 text-xs font-bold text-primary">{ca.cart_number}</div>
                  <p className="text-sm">{(ca.contestants as any)?.profiles?.full_name ?? "Unknown"}</p>
                </div>
              </div>
            ))}
          </Section>

          <Section title="Caddy" icon={UserCheck} count={caddyAssignments?.length}>
            {showAdminActions && (
              <Button size="sm" variant="outline" className="w-full h-7 gap-1 text-[11px] mb-2" onClick={() => setShowCaddyDialog(true)}>
                <Plus className="h-3 w-3" /> Assign Caddy
              </Button>
            )}
            {caddyAssignments?.length === 0 && <EmptyState text="No caddies assigned" />}
            {caddyAssignments?.map((ca) => (
              <div key={ca.id} className="golf-card flex items-center justify-between p-3">
                <div>
                  <p className="text-sm font-medium">{(ca.contestants as any)?.profiles?.full_name ?? "Player"}</p>
                  <p className="text-xs text-muted-foreground">Caddy: {(ca.profiles as any)?.full_name ?? "Unknown"}</p>
                </div>
              </div>
            ))}
          </Section>
        </TabsContent>

        {/* PAIRINGS */}
        <TabsContent value="pairings" className="space-y-3 pt-2">
          {showAdminActions && (
            <div className="golf-card space-y-3 p-4">
              <h3 className="text-sm font-semibold flex items-center gap-2">
                <Shuffle className="h-4 w-4 text-primary" /> Generate Pairings
              </h3>
              <div className="grid grid-cols-3 gap-2">
                <div>
                  <Label className="text-[10px]">Start Type</Label>
                  <Select value={startType} onValueChange={setStartType}>
                    <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="tee_time">Tee Time</SelectItem>
                      <SelectItem value="shotgun">Shotgun</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label className="text-[10px]">First Tee</Label>
                  <Input type="time" value={firstTee} onChange={e => setFirstTee(e.target.value)} className="h-8 text-xs" />
                </div>
                <div>
                  <Label className="text-[10px]">Interval</Label>
                  <Input type="number" value={interval} onChange={e => setInterval(e.target.value)} className="h-8 text-xs" disabled={startType === "shotgun"} />
                </div>
              </div>
              <Button size="sm" className="w-full gap-1" onClick={handleGeneratePairings} disabled={generating}>
                <Shuffle className="h-3.5 w-3.5" />
                {generating ? "Generating…" : (event?.pairing_approval_required ? "Generate (Draft)" : "Generate & Publish")}
              </Button>
            </div>
          )}

          {/* Draft notice for organizer */}
          {event?.pairing_approval_required && pairings && pairings.length > 0 && showAdminActions && (
            <div className="golf-card border-accent/30 p-3">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-xs font-semibold text-accent">
                    Pairing dalam status Draft
                  </p>
                  <p className="text-[10px] text-muted-foreground">
                    Pemain belum bisa melihat group mereka
                  </p>
                </div>
                <Button size="sm" className="h-7 text-xs"
                  onClick={async () => {
                    await supabase
                      .from("events")
                      .update({ pairing_approval_required: false })
                      .eq("id", id!);
                    toast.success("Pairings dipublikasikan!");
                    queryClient.invalidateQueries({ queryKey: ["event", id] });
                  }}>
                  Publish
                </Button>
              </div>
            </div>
          )}

          {/* Non-organizer: show message if approval required */}
          {!showAdminActions && event?.pairing_approval_required && (
            <div className="golf-card p-6 text-center">
              <Clock className="mx-auto h-8 w-8 text-muted-foreground/40" />
              <p className="mt-2 text-sm text-muted-foreground">
                Pairing sedang dalam review
              </p>
              <p className="text-xs text-muted-foreground/60 mt-1">
                Tournament director akan segera mempublikasikan grup Anda
              </p>
            </div>
          )}

          {(!event?.pairing_approval_required || showAdminActions) && (
            <>
              {(!pairings || pairings.length === 0) && <EmptyState text="No pairings generated yet" />}
              {pairings?.map((p) => (
                <div key={p.id} className="golf-card p-3 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-semibold">Group {p.group_number}</span>
                    <div className="flex items-center gap-2">
                      {p.start_type === "shotgun" && p.start_hole && (
                        <Badge variant="outline" className="text-[10px] border-accent/30 text-accent">Hole {p.start_hole}</Badge>
                      )}
                      <span className="text-xs text-muted-foreground">{formatTeeTime(p.tee_time)}</span>
                    </div>
                  </div>
                  <div className="space-y-1">
                    {((p.pairing_players as any[]) ?? [])
                      .sort((a: any, b: any) => (a.position ?? 0) - (b.position ?? 0))
                      .map((pp: any) => (
                        <div key={pp.id} className="flex items-center gap-2 text-xs">
                          <span className="flex h-5 w-5 items-center justify-center rounded-full bg-primary/10 text-[10px] font-bold text-primary">{pp.position}</span>
                          <span className="truncate">{pp.contestants?.profiles?.full_name ?? "Unknown"}</span>
                          <span className="ml-auto text-muted-foreground">HCP {pp.contestants?.hcp ?? "—"}</span>
                        </div>
                      ))}
                  </div>
                </div>
              ))}
            </>
          )}
        </TabsContent>

        {/* LEADERBOARD */}
        <TabsContent value="leaderboard" className="space-y-2 pt-2">
          <div className="flex items-center justify-between mb-2">
            <p className="text-xs text-muted-foreground">{leaderboard?.length ?? 0} players</p>
            <Button size="sm" variant="ghost" className="h-7 gap-1 text-[10px]" onClick={() => refetchLeaderboard()}>
              <RefreshCw className="h-3 w-3" /> Refresh
            </Button>
          </div>

          {(!leaderboard || leaderboard.length === 0) && (
            <div className="golf-card p-6 text-center">
              <Trophy className="mx-auto h-8 w-8 text-muted-foreground/40" />
              <p className="mt-2 text-sm text-muted-foreground">No scores yet</p>
              {myContestant && isCheckedIn && (
                <Button size="sm" className="mt-3 gap-1" onClick={() => navigate(`/event/${id}/scorecard`)}>
                  <Pencil className="h-3.5 w-3.5" /> Be the first to enter scores
                </Button>
              )}
            </div>
          )}

          {leaderboard?.map((row, i) => (
            <div key={row.contestant_id} className="golf-card flex items-center gap-3 p-3">
              <div className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold ${
                i < 3 ? "bg-accent/20 text-accent" : "bg-muted text-muted-foreground"
              }`}>
                {row.rank_net ?? i + 1}
              </div>
              <div className="min-w-0 flex-1">
                <p className="text-sm font-medium truncate">{(row as any).profiles?.full_name ?? "Player"}</p>
                <p className="text-xs text-muted-foreground">HCP {row.hcp ?? "—"}</p>
              </div>
              <div className="text-right shrink-0">
                <p className="text-sm font-bold">{row.total_net ?? "—"}</p>
                <p className="text-[10px] text-muted-foreground">Gross {row.total_gross ?? "—"}</p>
              </div>
            </div>
          ))}

          <Button variant="outline" size="sm" className="w-full mt-2 gap-1 text-xs" onClick={() => navigate(`/event/${id}/leaderboard`)}>
            <Trophy className="h-3.5 w-3.5" /> Full Leaderboard
          </Button>
        </TabsContent>
      </Tabs>

      {/* Dialogs */}
      <AssignContestantDialog eventId={event.id} tourId={event.tour_id} open={showAssign} onOpenChange={setShowAssign} onDone={() => { setShowAssign(false); refetchContestants(); }} />
      <WinnerResultsDialog eventId={event.id} eventName={event.name} eventStatus={event.status} isOrganizer={!!isEventAdmin} open={showWinners} onOpenChange={setShowWinners} onDone={() => { setShowWinners(false); refetchResults(); }} />

      {/* Self Check-in Dialog */}
      <Dialog open={showCheckinDialog} onOpenChange={setShowCheckinDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Confirm Check-in</DialogTitle>
          </DialogHeader>
          <div className="space-y-2 text-sm">
            <p className="font-medium">{event.name}</p>
            <p className="text-muted-foreground">{(myContestant?.profiles as any)?.full_name}</p>
            <div className="golf-card p-3 space-y-1 mt-3">
              <p className="text-xs">Locker #: <span className="font-bold">{(checkins?.length ?? 0) + 101}</span></p>
              <p className="text-xs">Bag Drop #: <span className="font-bold">{(checkins?.length ?? 0) + 1}</span></p>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCheckinDialog(false)}>Cancel</Button>
            <Button onClick={handleSelfCheckin} disabled={checkingIn}>
              {checkingIn ? "Checking in…" : "Confirm Check-in"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Assign Cart Dialog */}
      <Dialog open={showCartDialog} onOpenChange={setShowCartDialog}>
        <DialogContent>
          <DialogHeader><DialogTitle>Assign Golf Cart</DialogTitle></DialogHeader>
          <div className="space-y-3">
            <div>
              <Label className="text-xs">Contestant</Label>
              <Select value={selectedContestantForCart} onValueChange={setSelectedContestantForCart}>
                <SelectTrigger className="h-9 text-xs"><SelectValue placeholder="Select player" /></SelectTrigger>
                <SelectContent>
                  {contestants?.map(c => (
                    <SelectItem key={c.id} value={c.id}>{(c.profiles as any)?.full_name ?? "Unknown"}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">Cart Number</Label>
              <Input type="number" value={cartNumber} onChange={e => setCartNumber(e.target.value)} placeholder="e.g. 1" className="h-9 text-xs" />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCartDialog(false)}>Cancel</Button>
            <Button onClick={handleAssignCart} disabled={!selectedContestantForCart || !cartNumber}>Assign</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Assign Caddy Dialog */}
      <Dialog open={showCaddyDialog} onOpenChange={setShowCaddyDialog}>
        <DialogContent>
          <DialogHeader><DialogTitle>Assign Caddy</DialogTitle></DialogHeader>
          <div className="space-y-3">
            <div>
              <Label className="text-xs">Contestant</Label>
              <Select value={selectedContestantForCaddy} onValueChange={setSelectedContestantForCaddy}>
                <SelectTrigger className="h-9 text-xs"><SelectValue placeholder="Select player" /></SelectTrigger>
                <SelectContent>
                  {contestants?.map(c => (
                    <SelectItem key={c.id} value={c.id}>{(c.profiles as any)?.full_name ?? "Unknown"}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">Caddy</Label>
              <Select value={selectedCaddy} onValueChange={setSelectedCaddy}>
                <SelectTrigger className="h-9 text-xs"><SelectValue placeholder="Select caddy" /></SelectTrigger>
                <SelectContent>
                  {clubStaff?.map((s: any) => (
                    <SelectItem key={s.user_id} value={s.user_id}>{(s.profiles as any)?.full_name ?? "Staff"} ({s.staff_role})</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCaddyDialog(false)}>Cancel</Button>
            <Button onClick={handleAssignCaddy} disabled={!selectedContestantForCaddy || !selectedCaddy}>Assign</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Finalize Confirmation Dialog */}
      <Dialog open={showFinalizeConfirm} onOpenChange={setShowFinalizeConfirm}>
        <DialogContent className="max-w-sm">
          <DialogHeader>
            <DialogTitle>Finalize Event?</DialogTitle>
            <DialogDescription className="text-xs space-y-1 pt-2">
              <p>Tindakan ini akan:</p>
              <ul className="list-disc pl-4 space-y-0.5">
                <li>Menghitung dan menyimpan pemenang</li>
                <li>Mengkoreksi Tournament HCP semua peserta</li>
                <li>Menutup event (tidak bisa dibuka lagi)</li>
              </ul>
              <p className="font-semibold pt-1">Pastikan semua scorecard sudah diinput.</p>
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setShowFinalizeConfirm(false)}>Batalkan</Button>
            <Button onClick={handleFinalizeEvent} disabled={finalizing}>
              {finalizing ? "Finalizing…" : "Ya, Finalize"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

// --- Helper Components ---
const Section = ({ title, icon: Icon, count, sub, children }: {
  title: string; icon: any; count?: number; sub?: string; children: React.ReactNode;
}) => (
  <div>
    <div className="flex items-center gap-2 mb-2">
      <Icon className="h-4 w-4 text-primary" />
      <h3 className="font-display text-sm font-semibold">{title}</h3>
      {count != null && <Badge variant="outline" className="text-[10px] ml-auto">{count}</Badge>}
      {sub && <span className="text-[10px] text-muted-foreground">{sub}</span>}
    </div>
    <div className="space-y-2">{children}</div>
  </div>
);

const EmptyState = ({ text }: { text: string }) => (
  <div className="golf-card p-6 text-center text-sm text-muted-foreground">{text}</div>
);

export default EventDetail;
